### PR TITLE
wrappers: extract core functionality

### PR DESCRIPTION
**Pull request by jacquerie**
This is the core library extracted from the work made by me and @MSusik. Apparently, this will not be needed anymore, but since I was working on it...

CC: @jirikuncar @kaplun @lnielsen @jalavik @jmartinm @tiborsimko @egabancho

### CODE REVIEW

**Comment by MSusik** [comment]
Can I merge it into another branch?

**Comment by jacquerie** [comment]
Sure! Should I refile the PR or are you going to do it the hard way?

**Comment by MSusik** [comment]
Whatever you prefer.

**Comment by jacquerie** [comment]
Let's go with refiling. Which branch should I push to?

**Comment by MSusik** [comment]
I created a branch `corefunctionality`

**Pull request closed without merging**
